import type { IBotStatusRepository } from "../../repositories/botStatusRepository";
import type { IButtonRoleRepository } from "../../repositories/buttonRoleRepository";
import type { IFeedbackRepository } from "../../repositories/feedbackRepository";
import type { IGuildConfigRepository } from "../../repositories/guildConfigRepository";
import type { IModActionRepository } from "../../repositories/modActionRepository";
import type { IReactionRoleRepository } from "../../repositories/reactionRoleRepository";
import type { ISessionRepository } from "../../repositories/sessionRepository";
import type { ITicketRepository } from "../../repositories/ticketRepository";
import type { IWarnRepository } from "../../repositories/warnRepository";
import type { IXpRepository } from "../../repositories/xpRepository";
import { BotStatusProvider } from "./botStatusProvider";
import { ButtonRoleProvider } from "./buttonRoleProvider";
import { FeedbackProvider } from "./feedbackProvider";
import { GuildConfigProvider } from "./guildConfigProvider";
import { ModActionProvider } from "./modActionProvider";
import { ReactionRoleProvider } from "./reactionRoleProvider";
import { SessionProvider } from "./sessionProvider";
import { TicketProvider } from "./ticketProvider";
import { WarnProvider } from "./warnProvider";
import { XpProvider } from "./xpProvider";

export const guildConfigRepository: IGuildConfigRepository = new GuildConfigProvider();
export const xpRepository: IXpRepository = new XpProvider();
export const reactionRoleRepository: IReactionRoleRepository = new ReactionRoleProvider();
export const buttonRoleRepository: IButtonRoleRepository = new ButtonRoleProvider();
export const warnRepository: IWarnRepository = new WarnProvider();
export const ticketRepository: ITicketRepository = new TicketProvider();
export const modActionRepository: IModActionRepository = new ModActionProvider();
export const sessionRepository: ISessionRepository = new SessionProvider();
export const feedbackRepository: IFeedbackRepository = new FeedbackProvider();
export const botStatusRepository: IBotStatusRepository = new BotStatusProvider();
