import { BotStatusProvider } from "./botStatusProvider";
import { FeedbackProvider } from "./feedbackProvider";
import { GuildConfigProvider } from "./guildConfigProvider";
import { ModActionProvider } from "./modActionProvider";
import { ReactionRoleProvider } from "./reactionRoleProvider";
import { SessionProvider } from "./sessionProvider";
import { TicketProvider } from "./ticketProvider";
import { WarnProvider } from "./warnProvider";
import { XpProvider } from "./xpProvider";

export const guildConfigRepository = new GuildConfigProvider();
export const xpRepository = new XpProvider();
export const reactionRoleRepository = new ReactionRoleProvider();
export const warnRepository = new WarnProvider();
export const ticketRepository = new TicketProvider();
export const modActionRepository = new ModActionProvider();
export const sessionRepository = new SessionProvider();
export const feedbackRepository = new FeedbackProvider();
export const botStatusRepository = new BotStatusProvider();
